title: Blog Bibliotheks- und Archivinformatik
author: Sebastian
email: sebastian.preher@stud.fhgr.ch
description: > # this means to ignore newlines
  Dritter Versuch eines Lerntagebuchs im Kurs Bibliotheks- und Archivinformatik FS2020

# social links

github_username:  NeedForSleepUndersheet2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
